name: "Spike"
description: "Time-boxed research to reduce uncertainty"
labels: ["type:spike"]
body:
  - type: textarea
    id: question
    attributes:
      label: Research question / decision to make
      placeholder: "Compare sqlite vs Postgres for local dev; pick one."
    validations:
      required: true
  - type: input
    id: timebox
    attributes:
      label: Timebox
      placeholder: "4 hours / 1 day"
    validations:
      required: true
  - type: textarea
    id: outcomes
    attributes:
      label: Definition of Done (deliverables)
      placeholder: "- Decision memo\n- PoC branch or notebook\n- Next steps"
    validations:
      required: true
