name: "Sprint Retrospective"
description: "Reflect on the last sprint and identify improvements"
labels: ["sprint-retro"]
body:
  - type: input
    id: sprint_name
    attributes:
      label: Sprint Name / Number
      placeholder: "Sprint 7"
    validations:
      required: true
  - type: textarea
    id: what_went_well
    attributes:
      label: What went well
      placeholder: "List at least 2 positives"
    validations:
      required: true
  - type: textarea
    id: what_can_improve
    attributes:
      label: What can improve
      placeholder: "List at least 2 areas to refine"
    validations:
      required: true
  - type: textarea
    id: action_items
    attributes:
      label: Action items
      placeholder: |
        - Next sprint: improve CI turnaround time
        - Next sprint: reduce scope to fit capacity
    validations:
      required: true
